eureka:
  client:
    service-url:
      #\u8BBE\u7F6E\u4E0EEureka Server\u4EA4\u4E92\u7684\u5730\u5740\uFF0C\u67E5\u8BE2\u670D\u52A1\u548C\u6CE8\u518C\u670D\u52A1\u90FD\u9700\u8981\u4F9D\u8D56\u8FD9\u4E2A\u5730\u5740\u3002\u9ED8\u8BA4\u662Fhttp://localhost:8761/eureka \uFF1B\u591A\u4E2A\u5730\u5740\u53EF\u4F7F\u7528 , \u5206\u9694\u3002
      defaultZone: http://localhost:8771/eureka/

server:
  port: 8060

spring:
  application:
    name: service-zuul

zuul:
  routes:
    #/api-a/ \u5F00\u5934\u5339\u914D\u5230service-producer
    api-a:
      path: /api-a/**
      serviceId: service-producer
    #/api-b/ \u5F00\u5934\u5339\u914D\u5230service-producer
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #\u5339\u914D/github/\u76F4\u63A5\u91CD\u5B9A\u5411\u5230https://github.com/
    github:
      path: /github/**
      url: https://github.com/

