eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka/

server:
  port: 8060

spring:
  application:
    name: service-zuul

zuul:
  routes:
    #/api-a/ \u5F00\u5934\u5339\u914D\u5230service-producer
    api-a:
      path: /api-a/**
      serviceId: service-producer
    #/api-b/ \u5F00\u5934\u5339\u914D\u5230service-producer
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #\u5339\u914D/github/\u76F4\u63A5\u91CD\u5B9A\u5411\u5230https://github.com/
    github:
      path: /github/**
      url: https://github.com/

