server:
  port: 8070

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8771/eureka/

#\u5F00\u542FHystrix
feign:
  hystrix:
    enabled: true